from __future__ import annotations

SOURCES = {
    "yfinance": {
        "type": "aggregator",
        "domains": ["instruments", "market", "corporate_actions", "fundamentals", "news"],
        "status": "candidate",
        "redundancy_group": "historical_market_aggregators",
    },
    "nse": {
        "type": "primary_exchange",
        "domains": ["instruments", "market", "corporate_actions", "company_events", "filings", "shareholding", "insider_transactions", "market_events", "indices"],
        "status": "candidate",
        "redundancy_group": "nse_access",
    },
    "nse_indices": {
        "type": "primary_exchange_http",
        "domains": ["indices", "sector_classification", "index_history", "index_valuation"],
        "status": "candidate",
        "redundancy_group": "nse_access",
    },
    "nse_public": {
        "type": "primary_exchange_http",
        "domains": ["shareholding", "insider_transactions", "market_events", "company_events", "indices"],
        "status": "candidate",
        "redundancy_group": "nse_access",
    },
    "indian-market-data": {
        "type": "open_source_wrapper",
        "domains": ["instruments", "market", "corporate_actions", "company_events", "indices", "market_events"],
        "status": "candidate",
        "redundancy_group": "nse_access",
    },
    "jugaad-data": {
        "type": "open_source_wrapper",
        "domains": ["market", "macro", "company_events", "indices"],
        "status": "candidate",
        "redundancy_group": "nse_access",
    },
    "niftyterminal": {
        "type": "open_source_wrapper",
        "domains": ["instruments", "market", "fundamentals", "indices", "documents"],
        "status": "candidate",
        "redundancy_group": "nse_access",
    },
    "NSEPython": {
        "type": "open_source_wrapper",
        "domains": ["market", "corporate_actions", "company_events", "indices"],
        "status": "candidate",
        "redundancy_group": "nse_access",
    },
    "nse_filings": {
        "type": "primary_exchange_http",
        "domains": ["filings", "documents", "fundamentals", "company_events", "governance", "shareholder_actions", "capital_raising", "regulatory_risk", "esg", "credit"],
        "status": "candidate",
        "redundancy_group": "nse_access",
    },
    "upstox": {
        "type": "broker_api",
        "domains": ["instruments", "market", "fundamentals", "shareholding", "corporate_actions"],
        "status": "installed_or_configured",
        "redundancy_group": "broker_data_api",
    },
    "fyers": {
        "type": "broker_api",
        "domains": ["market", "instruments"],
        "status": "candidate",
        "redundancy_group": "broker_data_api",
    },
    "dhan": {
        "type": "broker_api",
        "domains": ["market", "instruments"],
        "status": "candidate",
        "redundancy_group": "broker_data_api",
    },
    "angel_one": {
        "type": "broker_api",
        "domains": ["market", "instruments"],
        "status": "candidate",
        "redundancy_group": "broker_data_api",
    },
    "zerodha": {
        "type": "broker_api",
        "domains": ["market", "instruments"],
        "status": "candidate",
        "redundancy_group": "broker_data_api",
    },
    "google_news_rss": {
        "type": "rss_aggregator",
        "domains": ["news"],
        "status": "candidate",
        "redundancy_group": "news_aggregators",
    },
    "economic_times_rss": {
        "type": "publisher_rss",
        "domains": ["news"],
        "status": "candidate",
        "redundancy_group": "publisher_rss",
    },
    "business_standard_rss": {
        "type": "publisher_rss",
        "domains": ["news"],
        "status": "candidate",
        "redundancy_group": "publisher_rss",
    },
    "stoxim": {
        "type": "structured_fundamentals",
        "domains": ["fundamentals", "shareholding", "corporate_actions", "company_events"],
        "status": "candidate",
        "redundancy_group": "fundamentals_sources",
    },
    "sebi": {
        "type": "regulator",
        "domains": ["regulatory", "filings", "company_events", "insider_transactions"],
        "regulatory_capabilities": ["legal", "regulations", "circulars", "master_circulars", "orders", "informal_guidance", "press_releases", "news_listing"],
        "status": "candidate",
        "redundancy_group": "regulatory_docs",
    },
    "mospi": {
        "type": "primary_macro",
        "domains": ["macro", "cpi", "iip"],
        "status": "candidate",
        "redundancy_group": "macro",
    },
    "rbi": {
        "type": "primary_macro",
        "domains": ["macro"],
        "status": "candidate",
        "redundancy_group": "macro",
    },
    "amfi": {
        "type": "primary_fund_data",
        "domains": ["fund_data"],
        "status": "out_of_scope_v1",
        "redundancy_group": "fund_data",
    },
    "mftool": {
        "type": "open_source_wrapper",
        "domains": ["fund_data"],
        "status": "out_of_scope_v1",
        "redundancy_group": "fund_data",
    },
}
